services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: netscan
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: netscan
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    environment:
      NSO_DATABASE_URL: postgresql+psycopg://postgres:netscan@db:5432/netscan
      NSO_OUTPUT_DIR: /data/outputs
      NSO_NMAP_PATH: nmap
    volumes:
      - outputs:/data/outputs
    depends_on:
      - db
    cap_add:
      - NET_RAW
      - NET_ADMIN

  gateway:
    build:
      context: .
      dockerfile: docker/Dockerfile.gateway
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  dbdata:
  outputs:
