services:
  db:
    image: public.ecr.aws/bitnami/postgresql:16
    environment:
      POSTGRES_DB: netscan
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: netscan
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    environment:
      NSO_DATABASE_URL: postgresql+psycopg://postgres:netscan@db:5432/netscan
      NSO_OUTPUT_DIR: /data/outputs  # default: ./data/outputs
      NSO_NMAP_PATH: nmap           # default: nmap
    volumes:
      - outputs:/data/outputs
    depends_on:
      - db
    cap_add:
      - NET_RAW
      - NET_ADMIN

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    volumes:
      - ./ops/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api

volumes:
  dbdata:
  outputs:
