name: ci-cd

on:
  push:
    branches: [main]
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install documentation dependencies
        run: pip install mkdocs mkdocs-myst-parser mkdocs-linkcheck
      - name: Build documentation
        run: mkdocs build --strict
      - name: Check documentation links
        run: mkdocs linkcheck
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit pytest pytest-cov
      - name: Run pre-commit
        run: pre-commit run --all-files
      - name: Run tests
        run: pytest
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Ensure docs updated
        run: python tools/check_docs_sync.py

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & (on main) push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.backend
          platforms: linux/amd64
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/${{ toLower(github.repository) }}:latest

  # optional: separate deploy job triggering your server
